version: "3.9" # Docker Engine release 19.03.0+ [https://docs.docker.com/compose/compose-file/]

services:
  web:
    build: .
    restart: always
    container_name: aurora_front
    ports:
      - 5001:3000
